Repository wecount-dev/wecount, pull requests merged in 2021-09, with the labels that each got.

#102 Enhance [Profile] and user data
  assets/images/no_profile.png
  assets/images/no_profile@2x.png
  assets/images/no_profile@3x.png
  assets/translations/en.json
  assets/translations/ko.json
  package.json
  prisma/schema.prisma
  public/index.html
  rollup.config.js
  src/App.svelte
  src/components/navigations/Main/Header/AuthHeader.svelte
  src/components/navigations/Main/Header/MainHeader/Profile.svelte
  src/components/navigations/Main/Header/MainHeader/Serach.svelte
  src/components/navigations/Main/Header/MainHeader/index.svelte
  src/components/navigations/Main/Header/index.svelte
  src/components/pages/Feed/Feed.svelte
  src/components/pages/Feed/FeedCard.svelte
  src/components/pages/Profile.svelte
  src/components/uis/ImageUpload.svelte
  src/services/storageService.ts
  src/services/userService.ts
  src/stores/sessionStore.ts
  src/types/supabase.ts
  src/utils/Icon.ts
  yarn.lock
Labels: 🍗 enhancement, 🔧 refactor

#103 Update community drawer component routing
  src/components/navigations/Community/Drawer/Menu.svelte
  src/components/navigations/Community/Drawer/index.svelte
  src/components/pages/dashboard/MemberCard.svelte
Labels: 🍗 enhancement

#106 Set default export components
  src/App.svelte
  src/components/navigations/Community/Drawer/index.ts
  src/components/navigations/Community/index.svelte
  src/components/navigations/Community/index.ts
  src/components/navigations/Main/Header/MainHeader/index.ts
  src/components/navigations/Main/Header/index.svelte
  src/components/navigations/Main/Header/index.ts
  src/components/navigations/Main/index.svelte
  src/components/navigations/Main/index.ts
Labels: 🔧 refactor

#109 Corrected 404 error related to main.ts.
  rollup.config.js
Labels: 🛠 bugfix

#110 Refactor codebase and integrate `createCommunity` api
  assets/translations/en.json
  assets/translations/ko.json
  package.json
  src/components/pages/Member/MembershipRequestList.svelte
  src/components/pages/Profile.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/community/CommunityCreate.svelte
  src/components/uis/Button.svelte
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
  src/services/communityService.ts
  src/utils/colors.ts
  yarn.lock
Labels: 🔧 refactor, 🎯 feature

#111 Add `loading` status in [Button]
  src/components/pages/SignIn.svelte
  src/components/uis/Button.svelte
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
Labels: 🍗 enhancement
