Repository wecount-dev/wecount, pull requests merged in 2021-08, with the labels that each got.

#11 Deploy to staging url on merge
  .github/workflows/deploy.yml
Labels: 💨 ci, 🚚 deploy

#12 Setup firebase hosting on release created
  .firebaserc
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-staging.yml
  README.md
  firebase.json
  public/404.html
Labels: 💨 ci, 🚚 deploy

#13 Include firebase functions to project
  firebase.json
  functions/.gitignore
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.json
  functions/yarn.lock
Labels: :hammer_and_pick: integration

#9 Implement pages in Auth route
  .eslintrc.js
  assets/en.json
  assets/ko.json
  assets/svgs/check.svg
  assets/svgs/key.svg
  assets/svgs/logo.svg
  assets/svgs/mail.svg
  assets/translations/en.json
  assets/translations/ko.json
  environment.d.ts
  jest.config.js
  package.json
  postcss.config.js
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/favicon.png
  public/global.css
  public/index.html
  public/site.webmanifest
  rollup.config.js
  src/App.svelte
  src/components/navigations/Auth.svelte
  src/components/navigations/Main.svelte
  src/components/pages/Intro.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/__tests__/__snapshots__/Intro.test.ts.snap
  src/components/uis/Button.svelte
  src/components/uis/EditText.svelte
  src/components/uis/__tests__/Button.test.ts
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
  src/i18n.ts
  src/utils/Icon.ts
  svelte.config.js
  tsconfig.json
  yarn.lock
Labels: 🎯 feature

#19 Fix VSCode environment for postcss
  .vscode/settings.json
  src/components/pages/Intro.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/__tests__/__snapshots__/Intro.test.ts.snap
  src/components/uis/Button.svelte
  src/components/uis/EditText.svelte
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
Labels: :desktop_computer: developer environment, ✨ config

#21 Enhance responsive design for auth pages in mobile
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
Labels: 🍗 enhancement

#22 Refactor routes and change auth flow
  .eslintignore
  .vscode/settings.json
  __mocks__/svelte-spa-router.ts
  assets/translations/en.json
  assets/translations/ko.json
  src/App.svelte
  src/components/navigations/Auth.svelte
  src/components/navigations/Main.svelte
  src/components/pages/Intro.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/__tests__/__snapshots__/Intro.test.ts.snap
  src/components/uis/Button.svelte
  src/components/uis/Header.svelte
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
Labels: 🔧 refactor

#14 [Modal] UI component Implementation
  src/components/uis/Modal.svelte
Labels: ♢ ui component, 🎯 feature

#25 Resolve a typescript error in functions
  functions/.eslintrc.js
  functions/.gitignore
Labels: ❄️ types

#29 Create Select Component
  assets/svgs/arrow-down.svg
  src/components/uis/Select.svelte
  src/utils/Icon.ts
Labels: 🎯 feature

#27 Set up a paypal sdk with function and impl one-time payment
  .firebaserc
  functions/.eslintrc.js
  functions/.gitignore
  functions/.prettierrc.js
  functions/config.ts
  functions/env.sample.json
  functions/environment.d.ts
  functions/index.ts
  functions/package.json
  functions/src/app.ts
  functions/src/index.ts
  functions/src/paypal/captureOrder.ts
  functions/src/paypal/client.ts
  functions/src/paypal/createOrder.ts
  functions/src/paypal/index.ts
  functions/src/paypal/refundOrder.ts
  functions/tsconfig.json
  functions/yarn.lock
Labels: 🎯 feature

#41 Implment MemberList
  assets/svgs/badge-crown.svg
  assets/svgs/trash-can.svg
  assets/translations/en.json
  assets/translations/ko.json
  src/components/uis/MemberList.svelte
  src/utils/Icon.ts
Labels: 🎯 feature

#45 Add feature : Select component multiple option
  src/components/uis/Select.svelte
Labels: 🍗 enhancement

#46 Utilize Prisma with supabase postgres and build services
  .eslintignore
  .gitignore
  dotenv/.env.sample
  package.json
  prisma/migrations/20210807170433_user_community/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/App.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/Temp.svelte
  src/services/communityService.ts
  src/services/userService.ts
  yarn.lock
Labels: 🚧 experimental, 🚽 migration

#54 Refactor [Button]
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/__tests__/__snapshots__/Intro.test.ts.snap
  src/components/uis/Button.svelte
  src/components/uis/__tests__/__snapshots__/Button.test.ts.snap
Labels: 🍗 enhancement, 🔧 refactor

#62 [Feature] ImageUpload component & uploadImage service
  assets/svgs/upload_close.svg
  assets/svgs/upload_plus.svg
  package.json
  src/components/uis/ImageUpload.svelte
  src/services/storageService.ts
  src/utils/Icon.ts
  yarn.lock
Labels: 🎯 feature

#67 [Feature] ProgressBar component
  src/components/uis/ProgressBar.svelte
Labels: 🎯 feature

#69 [Feature] Global typographies
  src/App.svelte
Labels: 🎯 feature

#64 Specify prisma schema and impl service layer
  .eslintignore
  package.json
  prisma/migrations/20210807170433_user_community/migration.sql
  prisma/migrations/20210818042513_init/migration.sql
  prisma/schema.prisma
  rollup.config.js
  src/App.svelte
  src/components/navigations/Main.svelte
  src/components/pages/ServiceSample.svelte
  src/components/uis/Card.svelte
  src/components/uis/Carousel.svelte
  src/components/uis/Header.svelte
  src/services/communityService.ts
  src/services/feedService.ts
  src/services/permissionService.ts
  src/services/userService.ts
  src/types/index.svelte
  src/types/index.ts
  src/types/supabase.ts
  yarn.lock
Labels: 🎯 feature, :small_red_triangle: schema

#68 [Feature] TabNavigation component
  src/components/pages/Temp.svelte
  src/components/uis/TabNavigation.svelte
  src/types/index.ts
Labels: 🎯 feature

#38 Implement the drawer component
  assets/svgs/chevrons_left.svg
  assets/svgs/menu.svg
  assets/svgs/plus.svg
  assets/translations/en.json
  assets/translations/ko.json
  src/App.svelte
  src/components/uis/Drawer/CommunityMenu.svelte
  src/components/uis/Drawer/CommunityPlusMenu.svelte
  src/components/uis/Drawer/Drawer.svelte
  src/components/uis/Drawer/Menu.svelte
  src/components/uis/Drawer/SelectIconButton.svelte
  src/types/index.ts
  src/utils/Icon.ts
Labels: 🎯 feature, ♢ ui component

#81 [Feature] Community creation page
  assets/translations/en.json
  assets/translations/ko.json
  src/App.svelte
  src/components/navigations/Main.svelte
  src/components/pages/community/Asterisk.svelte
  src/components/pages/community/Carousel.svelte
  src/components/pages/community/Create.svelte
  src/components/pages/community/InputContainer.svelte
  src/components/uis/ArrowButton.svelte
  src/components/uis/Button.svelte
  src/components/uis/Card.svelte
  src/components/uis/CommunityCard.svelte
  src/types/index.ts
Labels: 🎯 feature, ♢ ui component

#77 [Feature] Circle progress bar
  src/components/uis/CircleProgressBar.svelte
  src/components/uis/TripleCircleProgressBar.svelte
Labels: 🎯 feature, ♢ ui component

#86 [Feature] Implement header manipulation
  assets/svgs/bell.svg
  assets/svgs/search.svg
  assets/translations/en.json
  assets/translations/ko.json
  src/components/navigations/Main.svelte
  src/components/uis/CircleImage.svelte
  src/components/uis/header/Index.svelte
  src/components/uis/header/Manipulation.svelte
  src/components/uis/header/Profile.svelte
  src/components/uis/header/Serach.svelte
  src/utils/Icon.ts
Labels: 🎯 feature, ♢ ui component

#87 [Feature] Implement community router
  src/components/navigations/Community.svelte
  src/components/navigations/Main.svelte
  src/components/uis/Drawer/Drawer.svelte
  src/components/uis/header/Index.svelte
Labels: 🎯 feature

#98 Refactor `Index` to lowercase
  .github/workflows/ci.yml
  .vscode/settings.json
  jest.config.js
  package.json
  rollup.config.js
  src/components/navigations/Main.svelte
  src/components/uis/Header.svelte
  src/components/uis/drawer/index.svelte
  src/components/uis/header/index.svelte
  src/i18n.ts
  yarn.lock
Labels: 🔧 refactor

#94 Changed landing page and set dark theme shortcuts
  assets/translations/en.json
  assets/translations/ko.json
  src/App.svelte
  src/components/navigations/Main.svelte
  src/components/pages/Intro.svelte
  src/components/pages/Onboarding.svelte
  src/components/pages/__tests__/Intro.test.ts
  src/components/pages/__tests__/__snapshots__/Intro.test.ts.snap
  src/components/uis/header/Manipulation.svelte
  src/components/uis/header/Profile.svelte
  src/components/uis/header/Serach.svelte
  src/components/uis/header/index.svelte
Labels: 🍗 enhancement, 🎯 feature

#93 [Feature] Implement Feed Screen
  assets/svgs/arrow_left.svg
  assets/svgs/arrow_right.svg
  assets/svgs/minus_circle_fill.svg
  assets/svgs/plus_circle_fill.svg
  assets/svgs/shopping_bag.svg
  assets/translations/en.json
  assets/translations/ko.json
  package.json
  src/App.svelte
  src/components/navigations/Community.svelte
  src/components/navigations/Main.svelte
  src/components/pages/Feed/Feed.svelte
  src/components/pages/Feed/FeedCard.svelte
  src/components/pages/Member/Member.svelte
  src/components/pages/ServiceSample.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/Temp.svelte
  src/components/uis/FeedCreatePopup.svelte
  src/components/uis/ImageUpload.svelte
  src/components/uis/Modal.svelte
  src/components/uis/Pictures.svelte
  src/components/uis/PicturesModal.svelte
  src/utils/Icon.ts
  yarn.lock
Labels: 🎯 feature

#99 Organize media query with var
  package.json
  postcss.config.js
  public/404.html
  rollup.config.js
  src/App.svelte
  src/components/navigations/Main.svelte
  src/components/pages/Member/Member.svelte
  src/components/pages/Member/MemberList.svelte
  src/components/pages/Member/MembershipRequestList.svelte
  src/components/pages/Onboarding.svelte
  src/components/pages/SignIn.svelte
  src/components/pages/SignUp.svelte
  src/components/pages/community/Carousel.svelte
  src/components/pages/community/Create.svelte
  src/components/pages/community/InputContainer.svelte
  src/components/pages/dashboard/Index.svelte
  src/components/pages/dashboard/MemberContainer.svelte
  src/components/pages/dashboard/UsageDetailCard.svelte
  src/components/uis/Card.svelte
  src/components/uis/FeedCreatePopup.svelte
  src/components/uis/drawer/index.svelte
  src/components/uis/header/Manipulation.svelte
  yarn.lock
Labels: 🍗 enhancement

#100 Refactor folder structures
  .vscode/extensions.json
  .vscode/settings.json
  src/App.svelte
  src/components/navigations/Community/Drawer/CommunityMenu.svelte
  src/components/navigations/Community/Drawer/CommunityPlusMenu.svelte
  src/components/navigations/Community/Drawer/Menu.svelte
  src/components/navigations/Community/Drawer/SelectIconButton.svelte
  src/components/navigations/Community/Drawer/index.svelte
  src/components/navigations/Community/index.svelte
  src/components/navigations/Main/Header/Manipulation.svelte
  src/components/navigations/Main/Header/Profile.svelte
  src/components/navigations/Main/Header/Serach.svelte
  src/components/navigations/Main/Header/index.svelte
  src/components/navigations/Main/index.svelte
  src/components/pages/community/CommunityCreate.svelte
Labels: 🔧 refactor
