Repository wecount-dev/wecount, pull requests merged in 2021-12, with the labels that each got.

#118 Migrate pkg manager to yarn2
  .editorconfig
  .gitignore
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: 🚽 migration

#119 Refactor EditText with css grid
  src/components/uis/EditText.svelte
Labels: 🍗 enhancement

#122 Temporarily fix routing removing $goto
  .routify/routes.default.js
  src/layouts/community-item.svelte
  src/routes/community/[id]/sidebar/index.svelte
  src/routes/index.svelte
Labels: 🛠 bugfix, :roll_eyes: workaround

#123 Backup current work
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-staging.yml
  .routify/bundles/_default-bundle.js
  .routify/bundles/_default_community__id_-bundle.js
  .routify/routes.default.js
  package.json
  src/App.svelte
  src/layouts/header/index.svelte
  src/layouts/header/main/index.svelte
  src/routes/_module.svelte
  src/routes/auth/sign-in.svelte
  src/routes/profile.svelte
  vite.config.js
  yarn.lock
Labels: 🍗 enhancement, 🛠 bugfix

#124 Migrate db tables and change default storage path
  .env.d.ts
  .env.sample
  package.json
  prisma/migrations/20211227130305_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/services/storageService.ts
  src/types/supabase.ts
  yarn.lock
Labels: 🚽 migration

#125 Design `feed-item` as a starter
  global.css
  package.json
  src/layouts/community-item.svelte
  src/layouts/feed-item.svelte
  src/routes/community/[id]/feeds.svelte
  yarn.lock
Labels: 💅 design

#126 Add design to `feed` route
  .routify/routes.default.js
  src/layouts/feed-item.svelte
  src/layouts/image-collection.svelte
  src/routes/community/[id]/_module.svelte
  src/routes/community/[id]/feeds.svelte
  src/services/feedService.ts
Labels: 💅 design

#127 Design [Settings] route
  .routify/routes.default.js
  assets/langs/en.json
  assets/langs/ko.json
  assets/svgs/no_profile.svg
  assets/svgs/trash.svg
  assets/svgs/trash_can.svg
  global.css
  prisma/migrations/20211227152758_init/migration.sql
  prisma/schema.prisma
  src/layouts/__tests__/__snapshots__/button.test.ts.snap
  src/layouts/button.svelte
  src/layouts/community-item.svelte
  src/layouts/input-box.svelte
  src/layouts/user-image.svelte
  src/routes/community/[id]/members.svelte
  src/routes/community/[id]/settings/_module.svelte
  src/routes/community/[id]/settings/index.svelte
  src/routes/community/[id]/settings/members.svelte
  src/routes/community/[id]/settings/members/index.svelte
  src/routes/community/[id]/settings/members/member-item.svelte
  src/routes/community/[id]/settings/members/register-item.svelte
  src/routes/profile.svelte
  src/types/supabase.ts
  src/utils/icons.ts
Labels: 💅 design

#128 feat: Add feed popup
  .routify/routes.default.js
  assets/langs/en.json
  assets/langs/ko.json
  assets/svgs/close.svg
  src/layouts/edit-text.svelte
  src/layouts/modal.svelte
  src/layouts/uploadable-photo-card.svelte
  src/routes/auth/sign-up.svelte
  src/routes/community/[id]/feeds/add.svelte
  src/routes/community/[id]/feeds/index.svelte
  src/utils/icons.ts
Labels: 💅 design

#129 Integrate minimal data to dashboard
  src/layouts/community-card.svelte
  src/layouts/onboard-card.svelte
  src/routes/community/[id]/dashboard/history.svelte
  src/routes/community/[id]/dashboard/index.svelte
  src/routes/community/[id]/dashboard/summary.svelte
  src/routes/community/[id]/sidebar/index.svelte
  src/routes/index.svelte
  src/services/communityService.ts
Labels: 🍗 enhancement
